### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'collapseValue')

### ISSUE THREAD

**Issue by jonasstrehle** [unyt-org/uix#196]
When running the deployment project (`uixdev --init test --template deployment`) with the uix@0.3.x, the following exception is thrown:

```ts
TypeError: Cannot read properties of undefined (reading 'collapseValue')
    at readDXConfigData (https://dev.cdn.unyt.org/uix1/src/app/dx-config-parser.ts:11:67)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async getDXConfigData (https://dev.cdn.unyt.org/uix1/src/app/dx-config-parser.ts:50:85)
    at async runBackends (https://dev.cdn.unyt.org/uix1/run.ts:173:75)
    at async https://dev.cdn.unyt.org/uix1/run.ts:159:1
```

This does not happen in the UIX@0.2.x version. Any idea why Datex is not loaded yet @benStre?

**Comment by benStre** [comment]
I could not reproduce this using the dev cdn and deno for UIX. Has this already been fixed?

**Comment by jonasstrehle** [comment]
was because of old runner
