### ISSUE TITLE
Imports from the `sass` namespace prevent UIX from initial startup

### ISSUE THREAD

**Issue by nwLSteam** [unyt-org/uix#96]
### 🕗 Version & Regression Information

```
UIX v0.1.55 (https://cdn.unyt.org/uix/)

DATEX Core:  v0.0.55 (https://cdn.unyt.org/datex-core-js-legacy/)
Deno:        1.39.4
TypeScript:  5.3.3
V8:          12.0.267.8
```
I run UIX with `uix -wlb`.

### 💻 Code

See https://github.com/nwLSteam/uix-mve-sass-namespace, especially `/frontend/entrypoint.scss`.

### 🙂 Expected behavior

I expect the project to compile on the first startup.

### 🙁 Actual behavior

The project compile fails entirely, the backend doesn't even start.

```
error: Uncaught (in promise) TypeError: Invalid URL: './' with base 'sass:color.scss'
                super(path, base);
                ^
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:389:27)
    at new Path (https://cdn.unyt.org/uix@0.1.x/src/utils/path.ts:19:3)
    at Path.get parent_dir (https://cdn.unyt.org/uix@0.1.x/src/utils/path.ts:214:48)
    at Path.isChildOf (https://cdn.unyt.org/uix@0.1.x/src/utils/path.ts:433:15)
    at Transpiler.resolveRelativeSrcPath (https://cdn.unyt.org/uix@0.1.x/src/server/transpiler.ts:210:23)
    at Transpiler.updateFile (https://cdn.unyt.org/uix@0.1.x/src/server/transpiler.ts:302:24)
    at Transpiler.loadSCSSDependencies (https://cdn.unyt.org/uix@0.1.x/src/server/transpiler.ts:409:28)
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async Transpiler.transpileSCSS (https://cdn.unyt.org/uix@0.1.x/src/server/transpiler.ts:362:9)
```

To get the project to work, you have to
- remove the `@use 'sass:color'` line in entrypoint.scss
- wait for the system to start
- **add back** the `@use 'sass:color'` line in entrypoint.scss

You can confirm that the import succeeded by visiting the website and checking the (modified) color of the element.

**Comment by jonasstrehle** [comment]
Thanks for your detailed issue.
I guess we didn’t thought about (build-in) modules for SCSS so far @benStre. We will investigate and get back to you.

**Comment by jonasstrehle** [comment]
This bugfix will be part of the next UIX release.
